### ISSUE TITLE
keypad macros are prefixed with KC

### ISSUE THREAD

**Issue by nico202** [mihaiolteanu/mugur#8]
According to [this](https://beta.docs.qmk.fm/using-qmk/simple-keycodes/keycodes_basic#number-pad), the correct symbol for keypad plus is KC_KP_PLUS (build was failing for me with KP_PLUS), same goes for other keypad-related symbols.

If anybody can reproduce I will submit a patch

**Comment by mihaiolteanu** [comment]
Of course, `(error "Invalid mugur key, kp7")`.
Definitely an error. It should be KC_KP and **not** KP_.
